### ISSUE TITLE
Fail if tag is older than base version

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#105]
As long as you have binary-breaking changes on a branch, then tagging a non-breaking version number will fail the bincompat checks.

However, currently in sbt-typelevel the series/0.4 branch and main (base version 0.5) are actually binary-compatible, but semantically incompatible. So accidentally tagging 0.4.x on main would succeed in publishing, which is not what we want.

**Comment by rossabaker** [comment]
I just commented somewhere else, but I'd also like to be scolded if the base version is older than the latest tag on the branch.  I've seen MiMa failures at publish time because the new tag is the first time MiMa runs on new versions.

**Comment by armanbilge** [comment]
Yes, I replied there too 😉  that is already supported: if the base version is older than the latest tag, it will fail to start sbt.

**Comment by armanbilge** [comment]
@osleonard will work on this :)

**Comment by armanbilge** [comment]
@osleonard btw let me know if you need any more pointers, since this is a bug I'd really love to get this into the next release :)

Here's where do the check in the opposite direction, if the baseVersion is older than the latest tag:
https://github.com/typelevel/sbt-typelevel/blob/58ad2e745bf4cd6122e1c88a2d4f3610876fab96/versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala#L76-L83
