### ISSUE TITLE
sbt-rewarn integration?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#110]
TIL about https://github.com/rtimush/sbt-rewarn.

> By default, sbt shows compilation warnings only for the source files that have been re-compiled in the current incremental compilation run. sbt-rewarn makes it print all warnings on every compilation, even if you didn't change anything.

> This is particularly helpful if you want to keep your project warning-free. Simply enabling -Xfatal-warnings can be too annoying during development, especially the -Wunused:* family of warnings. The better alternative is to make warnings fatal on CI but not locally. Together with this plugin, you will always see if you have introduced any warnings, regardless of the incremental compilation.

**Comment by rossabaker** [comment]
That's a good find, but is there any reason not to run this as a global plugin?  Putting it in here is a big bet on its bincompat.

**Comment by armanbilge** [comment]
Yeah. You never know with these things 🙃 probably too niche, and it seems like it may be sneaking into the sbt-package to access some internal APIs.

**Comment by rossabaker** [comment]
I installed this globally and have been happy.

**Comment by armanbilge** [comment]
Cool! So do you think that's the way to go (we can mention it in our docs/faq) rather than shipping the plugin in sbt-typelevel?

**Comment by rossabaker** [comment]
Yes.
