### ISSUE TITLE
How should we handle transitive updates?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#113]
I'd like be mindful of how we provide transitive updates to our downstreams. I suppose this is a versioning question?

E.g. consider:
- https://github.com/typelevel/sbt-typelevel/pull/112

which didn't pass CI in https://github.com/typelevel/cats/pull/4120.

**Comment by rossabaker** [comment]
As a first cut, I like to mirror the dependencies:

* patch dep -> patch bump
* minor dep -> minor bump
* major dep -> major bump

Now, some libraries have different ideas of semver, and we might need to "correct" them.

The minor dep (someone else's new features) could just be a patch dep for us... but now we're cornered if our clients can't adopt the minorly bumped dep.

At the end of the day, it's about expressing the right amount of fear and trepidation downstream, but going at least as hard as our most frightened and trepidacious dependency did is a good start.

**Comment by armanbilge** [comment]
Works for me!
