### ISSUE TITLE
None site favicon using default config

### ISSUE THREAD

**Issue by danicheg** [typelevel/sbt-typelevel#121]
At the moment, generated microsites (with default site config from sbt-typelevel-site) don't contain a favicon. I guess that's because of an issue with resolving external links for favicons in the Laika.
https://github.com/typelevel/sbt-typelevel/blob/c7e198803c3bb3251738ae000bffb8e9bdf17876/site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala#L85
I could advise a straightforward fix to store favicon in a particular project but it isn't so handy. However, one can do it as a temporary workaround (we don't know how long it could be to fix that issue). WDYT?

**Comment by armanbilge** [comment]
Thanks for reminding me of this. It would be 💯 if someone could investigate the problem with Laika.

Anyway, I do know how we can fix this for all websites at once: sbt-http4s stores some extra files in the `resources/` folder:
https://github.com/http4s/sbt-http4s-org/tree/main/core/src/main/resources/org/http4s/sbt
Then, those resources are copied into the final website with this code:
https://github.com/http4s/sbt-http4s-org/blob/main/core/src/main/scala/org/http4s/sbt/Http4sOrgSitePlugin.scala#L43-L54

We can use the same technique here, to distribute the typelevel favicon via sbt-typelevel-site and automatically include it. WDYT?

**Comment by armanbilge** [comment]
I tried to fix it upstream:
- https://github.com/planet42/Laika/pull/250

**Comment by armanbilge** [comment]
Fixing this in Laika is a little more involved :) for now, we can fix this with the workaround I proposed in https://github.com/typelevel/sbt-typelevel/issues/121#issuecomment-1026018451.

**Comment by armanbilge** [comment]
A PR would be lovely! ❤️ 

What I propose is:
1. copy the default template from Laika in our own resources dir
  https://github.com/planet42/Laika/blob/e508502f38fb99c2167f9cae2fa0b208ab4083ea/io/src/main/resources
/laika/helium/templates/default.template.html
2. Set it up like sbt-http4s-org
  https://github.com/http4s/sbt-http4s-org/blob/0c6af8f3b5a1c26a15c9677584e267d6b0c7d270/core/src/main/scala/org/http4s/sbt/Http4sOrgSitePlugin.scala#L43-L54
3. Apply the patch to our copy of the template from https://github.com/planet42/Laika/pull/250
4. Uncomment the favicon code.

When we have our own copy of the template, we can actually make other improvements. For example, I've been wondering if we should have a list of Typelevel projects in the side panel like we do for http4s.
