### ISSUE TITLE
Rename `master` -> `main`

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#13]

**Comment by rossabaker** [comment]
I failed to give the team Write until now.  Was that blocking you from doing this?

**Comment by armanbilge** [comment]
To do that I think I need more than write. I can't access the settings panel at all, so can't change the default branch, add secrets, etc.

**Comment by rossabaker** [comment]
Most of the teams throughout the org have Write, but I just gave you additional Admin on this.

**Comment by armanbilge** [comment]
Thanks, done.
