### ISSUE TITLE
Proposal: explicit setting for disabling site publishing

### ISSUE THREAD

**Issue by danicheg** [typelevel/sbt-typelevel#137]
This was born from a discussion https://github.com/typelevel/log4cats/pull/603#pullrequestreview-870754763.

The site plugin contains the `tlSitePublishBranch` setting which could have a `None` value. But that would mean the site will still publishing just only for tags. There are cases when building the site is fine, but publishing is redundant. It's the case of the multibranch project without a versioned site. A versioned site for such projects could be redundant at all. So it would be nice to have the ability to disable site publishing from plugin settings. 
On the other hand, one can set `tlSitePublishBranch` to the `main` branch from which the site will be publishing, but it would be more clear if one can explicitly disable the publishing site.
So this proposal is just about getting more configurable behavior through explicit settings rather than getting functionality at all.

**Comment by armanbilge** [comment]
Yeah I was thinking this yesterday too. You are right that it is confusing. We could add a `tlSitePublishTags := true/false` setting but then raise an error if this is `true` and `tlSitePublishBranche := Some(...)` because you can only publish from one thing.

> There are cases when building the site is fine, but publishing is redundant. It's the case of the multibranch project without a versioned site.

Out of curiosity: if you are not publishing the site, is there a point to building it?

**Comment by danicheg** [comment]
> Out of curiosity: if you are not publishing the site from an old branch, is there a point to building it?

It's a sort of thin ice, I guess. The older branches shouldn't have docs (I mean site) then. But one day, a project may decide to have a versioned site. Then backporting it from upstream would be pretty painful.
