### ISSUE TITLE
bad option `-doc-external-doc` on Scala 3

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#166]
Noticed this in the Mouse 1.0.10 publish logs.
https://github.com/typelevel/mouse/runs/5172959686?check_suite_focus=true#step:14:186

```
[warn] bad option '-doc-external-doc:/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-core_3/2.7.0/cats-core_3-2.7.0.jar#http://typelevel.org/cats/api/,/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar#https://www.scala-lang.org/api/2.13.6/,/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-kernel_3/2.7.0/cats-kernel_3-2.7.0.jar#http://typelevel.org/cats/api/' was ignored
```

**Comment by armanbilge** [comment]
```
$ scaladoc --help
...
-doc-external-doc        Legacy option from Scala 2. Mapping betweeen path and external documentation. Use -external-mappings instead.
...
-external-mappings       Mapping between regexes matching classpath entries and external documentation. 'regex::[scaladoc|scaladoc|javadoc]::path' syntax is used
```

I assume this flag is added by `autoAPIMappings`, so I suspect this is something to be fixed upstream in sbt.

**Comment by armanbilge** [comment]
Linking to:
- https://github.com/sbt/sbt/issues/6652

**Comment by armanbilge** [comment]
I think mouse is missing some compatibility flags, since it only uses sbt-typelevel-ci-release (cc @danicheg). The configuration in sbt-typelevel-settings seem to do the right thing already, so we've already "fixed" this.

**Comment by danicheg** [comment]
@armanbilge Did you mean that Mouse should use sbt-typelevel (instead of sbt-typelevel-ci-release) to get things right about that 'bad option'?
Getting ahead of things, I've been trying changing Mouse dependencies, and none has changed.

**Comment by armanbilge** [comment]
@danicheg right, you could either just add `sbt-typelevel-settings` as an extra plugin or you could switch to `sbt-typelevel`. I originally chose `sbt-typelevel-ci-release` because the mouse build is fairly unusual and I didn't want to cause any extra disruption.

> Getting ahead of things, I've been trying changing Mouse dependencies, and none has changed.

Sorry, I couldn't understand. What did you try?

My hunch could be wrong of course, but then I can't understand why mouse has this problem that other projects do not.

**Comment by danicheg** [comment]
I've tried both options - added `sbt-typelevel-settings` to current plugins and used `sbt-typelevel` + `sbt-typelevel-site`.  
And `sbt ++3.0.2 doc` led to `[warn] bad option '-doc-external-doc:` in both.
