### ISSUE TITLE
sbt-header support?

### ISSUE THREAD

**Issue by rossabaker** [typelevel/sbt-typelevel#19]
One thing missing from sbt-spiewak is sbt-header support.  Maybe that's out of scope, but it's the first migration roadblock I hit.

**Comment by armanbilge** [comment]
See https://github.com/typelevel/sbt-typelevel/issues/16. I initially dropped it at @mpilquist's suggestion, but now I'm seeing there are two distinct markets: a ci-release plugin for e.g. @tpolecat and @mpilquist and a super-super plugin for @rossabaker (and me :).
