### ISSUE TITLE
`root / doc` passes but `unidoc / Scalaunidoc / doc` and `root / packageDoc` fail

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#214]
When using the `TypelevelUnidocPlugin` this can cause CI to pass in PRs but publishing to fail.

With many apologies to @timwspence who unwittingly uncovered this one in cats-stm 😆

In the cats-stm case, it comes down to the duplicate JVM/JS docs problem. Would be nice to fix that automatically as well.

**Comment by TimWSpence** [comment]
😂 I had noticed that the docs hadn't been published but thought I maybe hadn't pubished a new version since I fixed the build setup and didn't have time to check.

**Comment by armanbilge** [comment]
@TimWSpence yeah, you need to add something like:
```scala
ScalaUnidoc / unidoc / unidocProjectFilter := inAnyProject -- inProjects(root.js.aggregate: _*)
```

CI for the PR should have picked this up, but, you know, bugs 🙃
