### ISSUE TITLE
`apiURL` should be set for snapshot builds

### ISSUE THREAD

**Issue by DavidGregory084** [typelevel/sbt-typelevel#226]
Making a note of this so I don't forget!

Scaladoc inter-module linking does not seem to work unless the modules that you wish to link to have set `apiURL`. This causes this URL to be passed as a piece of external mapping configuration when Scaladoc is invoked. When this is missing, Scaladoc produces a warning as it cannot find any definition to link to.

At the moment `apiURL` is not set for snapshots or sbt plugins, because we link to [javadoc.io](https://javadoc.io) which does not support either. This means that snapshot builds for projects with inter-module Scaladoc links will fail in CI as fatal warnings is enabled by default.

For local builds (`githubIsWorkFlowBuild` is false) we could use `(crossTarget.value / "api").toURI.toURL`, as this is the output directory for Scaladoc.

It's possible we could use JAR URLs for snapshot builds, i.e.
```scala
val modName = moduleName.value
val host = sonatypeCredentialHost.value
val org = organization.value.replace(".", "/")
val mod = cross(modName)
val ver = version.value
val art = s"${modName}-${ver}-javadoc.jar"
url(s"jar:https://${host}/content/repositories/snapshots/${org}/${mod}/${ver}/${art}!/")
```
===>
```
jar:https://oss.sonatype.org/content/repositories/snapshots/org/typelevel/sbt-typelevel-docs_2.12/0.4.6-16-bc913e6-20220325T001241Z-SNAPSHOT/sbt-typelevel-docs-0.4.6-16-bc913e6-20220325T001241Z-SNAPSHOT-javadoc.jar!/
```

**Comment by armanbilge** [comment]
Thanks for tracking this down!

> It's possible we could use JAR URLs for snapshot builds, i.e.

Personally I liked this solution. If the artifacts are indeed published, those links should be legit and any Java-centric tool should in theory know what to do with them.

> For local builds (`githubIsWorkFlowBuild` is false) we could use `(crossTarget.value / "api").toURI.toURL`.

Right, although we should use this as a last resort in case someone is publishing outside of CI.

**Comment by DavidGregory084** [comment]
> Personally I liked this solution. If the artifacts are indeed published, those links should be legit and any Java-centric tool should in theory know what to do with them.

The downside IMO is that if someone is browsing a scaladoc for a snapshot that they have downloaded, these links will not work, but there are definitely limits to what we can do here!
<img width="789" alt="image" src="https://user-images.githubusercontent.com/2992938/160140537-c5946491-465e-4009-a4be-f19590dfab00.png">

> > For local builds (`githubIsWorkFlowBuild` is false) we could use `(crossTarget.value / "api").toURI.toURL`.
> 
> Right, although we should use this as a last resort in case someone is publishing outside of CI.
Oh yes good point! It seems weird to use this project and then do manual publishing but I'm sure there are folks who prefer to do manual releases so they can check everything in the staging repo.

**Comment by armanbilge** [comment]
> The downside IMO is that if someone is viewing a scaladoc for a snapshot that they have downloaded in a browser, these links will not work, but there are definitely limits to what we can do here! Also I guess we have to question how they would be doing that anyway, manually extracting a JAR?

I'd be curious if any IDE has an in-process javadoc viewer, such as IntelliJ. I.e., it downloads and lets you browse the docs from within the IDE itself. In that case I am hopeful that it can handle Jar URLs, and if not that it could be fixed pretty easily.

> It seems weird to use this project and then do manual publishing but I'm sure there are folks who prefer to do manual releases so they can check everything in the staging repo.

It's uncommon but important. For example, http4s releases patches for CVEs locally before pushing the code into the public repo. On the other hand, Some People™ keep their secret keys for publishing on air-gapped machines and whatnot 🤣 (looking at you Cats Effect :P)

**Comment by DavidGregory084** [comment]
Well there have been a lot of high-profile supply chain attacks recently so perhaps that is justified 😛

**Comment by armanbilge** [comment]
Well, I just couldn't leave well enough alone 🤣 

http://scaladoc-io.typelevel.workers.dev/raw/s01.oss.sonatype.org/content/repositories/snapshots/org/typelevel/sbt-typelevel-docs_2.12/0.5-df04bfa-SNAPSHOT/sbt-typelevel-docs_2.12-0.5-df04bfa-SNAPSHOT-javadoc.jar!/org/typelevel/sbt/CrossRootProject.html

**Comment by armanbilge** [comment]
Ok, confirmed that cats indeed has this problem too. Which is why fatal warnings are disabled for docs.

**Comment by armanbilge** [comment]
Just disabled fatal warnings for the unidocs artifact in https://github.com/typelevel/fs2/pull/2877. Maybe we should just do that.

**Comment by armanbilge** [comment]
Aha, here's another interesting solution!

jitpack.io is already pretty cool, but TIL that it also hosts javadoc. It clones/builds your repo on the fly. So this will work for any project hosted at GH, regardless of whether it publishes snapshots.

I tried this hash for fs2, but try swapping it one of your choice. Be patient! Took a few minutes for me.
https://javadoc.jitpack.io/com/github/typelevel/fs2/fs2-core_2.13/3c611842df6a9520038d7d1c35c02a4e99fcd676/javadoc/

**Comment by DavidGregory084** [comment]
Ohh, I had no idea it hosted javadoc, that's awesome!
