### ISSUE TITLE
Integrate w/ Laika 0.19

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#228]
To track the changes relevant to sbt-typelevel-site.

- [ ] https://github.com/planet42/Laika/pull/269
- [ ] https://github.com/planet42/Laika/pull/270
- [ ] https://github.com/planet42/Laika/issues/259
- [ ] https://github.com/planet42/Laika/issues/264
- [ ] https://github.com/planet42/Laika/issues/285
- [ ] https://github.com/planet42/Laika/pull/328

**Comment by jenshalm** [comment]
I hope this PR (https://github.com/planet42/Laika/pull/328) can convince you to add deprecating the `tlRelatedProjects` setting to the list above. It was useful when any customization would have required a custom template, but now the Helium API options are more flexible and generic than the this fairly prescriptive setting.

**Comment by armanbilge** [comment]
Thanks for the heads up, that looks like a nice change!
