### ISSUE TITLE
Warn in CI about passphrase-protected keys

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#23]
This is automatically supported (via a [workaround](https://github.com/typelevel/sbt-typelevel/blob/60549ca75a992b4898d318dd8dcff17c251ff5a3/.github/workflows/ci.yml#L121-L126)) to help migration, but I think we want to discourage it.

To force users to acknowledge this problem (and especially to prevent new users from making this mistake) we could require an opt-in sbt-setting to enable this legacy mode. But, some people might balk :)

We should also add docs explaining exactly how to install a key without a passphrase. I'm horrible and lazy, so I just make passphrase-less keys but I think you can also export a passphrased-key without the passphrase protection. Or #22 would help too.

**Comment by rossabaker** [comment]
I'd rather reduce friction for people so it Just Works.  We can moralize in the docs.

**Comment by armanbilge** [comment]
sounds good 👍
