### ISSUE TITLE
tlVersionIntroduced as a function of scalaVersion

### ISSUE THREAD

**Issue by rossabaker** [typelevel/sbt-typelevel#24]
Modules get introduced in different versions for different crossbuilds.  sbt-spiewak takes a function of Scala versions to version introduced:

```
    versionIntroduced := Map(
      "3.0.0-RC1" -> "1.0.0",
      "3.0.0-RC2" -> "1.0.1",
      "3.0.0-RC3" -> "1.1.3"
    ),
```

I'm not sure how we express that in `tlVersionIntroduced`.

**Comment by armanbilge** [comment]
I was thinking like:
```scala
.settings(
  tlVersionIntroduced := {
    if (tlIsScala3.value) Some("1.1.4") else None
  }
)
```

But, maybe not for everyone.

BTW, the mdoc build has a `crossSetting` helper to make defining version-specific settings even easier:
```scala
  scalacOptions ++= crossSetting(
    scalaVersion.value,
    if2 = List("-target:jvm-1.8", "-Yrangepos", "-deprecation"),
    if212 = List("-Xexperimental"),
    if211 = List("-Xexperimental"),
    if3 = List("-language:implicitConversions", "-Ximport-suggestion-timeout", "0")
  )
```

**Comment by armanbilge** [comment]
Yeah, the `Map` thing seems good actually. Should have done that, let me fix it.

**Comment by rossabaker** [comment]
I don't know without looking whether sbt-spiewak is a function or a map.  Maybe a function is more power than is needed.  I've always provided a map.

**Comment by armanbilge** [comment]
Yeah, I'm working on this now and I remembered why I don't like it: Scala version parsing from `String` and all its caveats, e.g. what if a user puts in "3.0" and "3.1" or just "3". I'd really rather just have something like this:

```
case class TLVersionIntroduced(
  scala212: Option[String] = None,
  scala213: Option[String] = None,
  scala3: Option[String] = None,
)
```

Or a solution like the `crossSetting` thing I posted above. Is there any reason we need to support Scala 3 RCs and stuff?

**Comment by rossabaker** [comment]
case-insensitive needed the RCs because it was checking old versions, but we could have just turned it off for Scala 3.  I removed it entirely in https://github.com/typelevel/case-insensitive/pull/208.

I don't like the case class, because that bundles binary compatibility of this plugin with the set of Scala versions supported today.  `crossSetting` looks dubious to me for a similar reason, though I don't know what it did under the hood.  I could be happy with pattern matching on `scalaBinaryVersion.value` as long as it recalculates itself when we switch Scala versions.

**Comment by armanbilge** [comment]
Oh, here's one more layer of complexity: now that we are checking MiMa for Scala.js and native as well, we also need to consider that axis, since these crosses were introduced later for some projects/modules. I guess that can be handled by defining a separate `tlVersionIntroduced` in `.jvmSettings` and `.jsSettings` etc., but there might be some duplication between those...

**Comment by rossabaker** [comment]
After questioning life choices that brought me to that point, I'd do separate `tlVersionIntroduced` settings.
