### ISSUE TITLE
SCM URLs in POM may be incorrect if publishing locally

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#249]
See https://github.com/typelevel/discipline/issues/332, where Vasil published Discipline from his local instead of with CI release.

**Comment by armanbilge** [comment]
Ross warned me about this in https://github.com/typelevel/sbt-typelevel/pull/31#discussion_r777224177. Woops.

**Comment by vasilmkd** [comment]
Relevant [comment](https://github.com/typelevel/discipline/issues/332#issuecomment-1094199781).

**Comment by armanbilge** [comment]
Yes, thanks. Maybe the plugin should check for upstream first before falling back to origin. Either that or we should disable this completely.
