### ISSUE TITLE
Flag `-Werror` set repeatedly on `0.4.8` version

### ISSUE THREAD

**Issue by danicheg** [typelevel/sbt-typelevel#253]
`0.4.8` contains some regression on compiling Scala 3 sources. 
Related failed CI builds: https://github.com/typelevel/log4cats/runs/5969372003?check_suite_focus=true#step:10:30, https://github.com/typelevel/keypool/runs/5969330317?check_suite_focus=true#step:9:28

**Comment by armanbilge** [comment]
Thanks for the report. I guess this broke everyone's build ...
