### ISSUE TITLE
What to do if a commit is tagged more than once?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#261]
In theory, it should be okay to tag the same commit as e.g. v0.1.0 and then again as v0.1.1 or v0.2.0 or even v1.0.0. Currently there's no special logic to handle this.

One option might be to use the highest version. However, if someone first tags v0.2.0 then retries as v0.1.1 it wouldn't work.

Another possibility is to try and introspect the exact tag that triggered the CI run, and use that. But this wouldn't work locally.

One more possibility is to use the newest tag, whatever that is.

**Comment by rossabaker** [comment]
What is the "newest" tag?  A lightweight tag has no date beyond the commit and author dates of the commit.  A tag object does, but most people don't even know those exist.

**Comment by armanbilge** [comment]
Oh, woops, I didn't really think about that. Then, seems the only reasonable choice is to use the highest-versioned tag, unless someone has another idea.

**Comment by armanbilge** [comment]
This will be hindered by https://github.com/typelevel/sbt-typelevel/issues/14, which I have put off fixing.
