### ISSUE TITLE
Add a status check job

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#290]
Some projects like to enforce that status checks pass before allowing a merge. You can configure this in GitHub, but you have to explicitly list which jobs you require to pass the checks. The problem is this list gets stale quickly: as soon as a Scala version updates, the job name changes (since it includes the Scala version) and it needs to be reconfigured.

So, easy solution: create a job with a stable name, that is empty, but has all other jobs as its dependency 😁

**Comment by fserra-mdsol** [comment]
I second that. This would prevent a PR that has a failed pipeline job to be (mistakenly?) merged, as it happened with me on `http4s-twirl`!

**Comment by armanbilge** [comment]
Sadly this is not as good a first issue as I thought. The Workflow DSL exposed via sbt-gh-actions is currently not quite expressive enough to what we need.

**Comment by armanbilge** [comment]
This can now be solved much more easily via https://github.com/typelevel/sbt-typelevel/issues/331 which will allow us to define stable job names.
