### ISSUE TITLE
Git Worktrees

### ISSUE THREAD

**Issue by zarthross** [typelevel/sbt-typelevel#309]
Would it be possible to update to the latest sbt-git?  The version used by this plugin does not work with 'git worktrees' and so interferes with my work flow.

See error:
```
org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
        at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1570)
```

**Comment by armanbilge** [comment]
Unfortunately the latest version of sbt-git was a breaking bump and I've been trying to put that off. However, I have been publishing milestones of sbt-typelevel 0.5.0 against the new sbt-git. The last milestone is a bit behind, let me cut a new one.

**Comment by armanbilge** [comment]
v0.5.0-M2 is now available on Maven Central.

https://github.com/typelevel/sbt-typelevel/releases/tag/v0.5.0-M2
