### ISSUE TITLE
Easy access to `currentRelease` and `currentPreRelease` 

### ISSUE THREAD

**Issue by majk-p** [typelevel/sbt-typelevel#318]
Hi!
First of all thanks for the great plugin, it simplifies the project setup a lot!

Lately, I've been setting up https://github.com/ocadotechnology/pass4s where I'm using `sbt-typelevel` for versioning, mima, publishing, and all that good stuff. For the website we have decided to go with docusaurus and mdoc as we already had it in our other project and wanted to be aligned.

For the docs, I wanted the mdoc `VERSION` to point to the latest stable. I've noticed it's already done in `sbt-typelevel-site` in the following lines:
https://github.com/typelevel/sbt-typelevel/blob/947ce2bf07ace1780010512ec7bf9369ab126f67/site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala#L111-L117

Unfortunately, there's no easy way to reuse it. After some trial and error, I've just decided to go with the following workaround 

```scala
def latestStableVersion = {
  import scala.sys.process._
  "git -c versionsort.suffix=- tag --list --sort=-version:refname"
    .!!
    .split("\n")
    .toList
    .map(_.trim)
    .filter(_.startsWith("v"))
    .head
}

/* and in project settings */
mdocVariables := Map(
  "VERSION" -> { if (isSnapshot.value) latestStableVersion else version.value }
),
```

Do you think it's feasible to extract the part about the latest stable release and prerelease as a public part to `sbt-typelevel-version` for this kind of use case?

**Comment by armanbilge** [comment]
Thanks! Yes, it probably makes sense to expose these in the versioning plugin.

I've had a few issues with these in the past, but I think they should be stable now. See:
- https://github.com/typelevel/sbt-typelevel/pull/198
- https://github.com/typelevel/sbt-typelevel/pull/282
