### ISSUE TITLE
v0.4.0

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#33]
https://github.com/typelevel/sbt-typelevel/milestone/1

This is more of a 0.1.0, except this is the next available version. In any case, what do we need to do to get here?

After the latest round of PRs merge I will probably migrate http4s-dom and feral.

## todo

- [x] steward support, merged but may need to be released?
      https://github.com/scala-steward-org/scala-steward/pull/2443
- [x] bikeshed all the names. I'd love to make more stuff private, but I'm scared of sbt.
       https://github.com/typelevel/sbt-typelevel/pull/80

**Comment by armanbilge** [comment]
Any feelings about cutting an `0.4.0-M1`? In any case I'm going to migrate my projects.

**Comment by armanbilge** [comment]
Did three migrations, fixed a couple bugs. My builds are all slimmer and better :)
- https://github.com/http4s/http4s-dom/pull/77
- https://github.com/typelevel/bobcats/pull/55
- https://github.com/typelevel/feral/pull/142

**Comment by armanbilge** [comment]
I'm going to try cutting `0.4.0-M1`, with the dreaded commit-and-tag push.

**Comment by armanbilge** [comment]
https://github.com/typelevel/sbt-typelevel/releases/tag/v0.4.0-M1

**Comment by armanbilge** [comment]
Confirmation that steward works with sbt-typelevel(-ci-release):
- https://github.com/tpolecat/doobie/pull/1634
- https://github.com/typelevel/bobcats/pull/59

**Comment by armanbilge** [comment]
Based on the discussion in https://github.com/typelevel/sbt-typelevel/issues/78#issuecomment-1015368180 I think we should go to v0.4.0 ASAP, since it's not viable to adopt sbt-typelevel without support from steward.

If/when we have to break, we can go to 0.5.0, NBD.

**Comment by rossabaker** [comment]
Agreed.

**Comment by armanbilge** [comment]
https://github.com/typelevel/sbt-typelevel/releases/tag/v0.4.0
