### ISSUE TITLE
Semantic version selector expressions

### ISSUE THREAD

**Issue by bpholt** [typelevel/sbt-typelevel#331]
Now that sbt 1.7 has been released with support for semantic version selector expressions (like `+ 2.13.x`), it would be nice if the generated YAML used the `.x` syntax and the specific versions were only specified in the sbt build definition. This would avoid having to update the YAML configs any time a Scala version update is merged.

**Comment by armanbilge** [comment]
Thanks for opening the issue! Yes I'm quite looking forward to this.

We can get this into 0.4.x behind a opt-in setting, or into 0.5 by default. 0.5 is imminent-ish, the current external blocker is the next Laika release which is also imminent-ish.

**Comment by armanbilge** [comment]
The other thing we need to be mindful of are projects that run CI against every Scala patch (e.g. compiler plugins).

**Comment by bpholt** [comment]
Yeah, seems like it would be wise to make it configurable. Maybe opt-in in 0.4 and then opt-out in 0.5?

**Comment by armanbilge** [comment]
Well, it can also be smart. e.g. if your `crossScalaVersions` has got multiple versions for the same Scala binary version, then it has to fallback. Otherwise it can use the semantic selector.

**Comment by armanbilge** [comment]
Until sbt-typelevel 0.5.x is available, a workaround is to set:
```scala
ThisBuild / githubWorkflowScalaVersions := Seq("2.13", "3")
```
