### ISSUE TITLE
Support CI matrices split across JVM/JS

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#34]
By default sbt-gh-actions generates a separate job for each scala/java version. However, many projects also have separate jobs for JVM/JS. Some thoughts:

1. Should we do this by default? Personally I like it because it's not always easy to tell from combined jobs whether a test failure occurred in JVM or JS if they are running the same tests. However, it increases the build matrix by 3 jobs, each which has some constant overhead. The decrease in CI time definitely worth for larger projects, but not so much for smaller ones.
2. To do this properly needs more support from sbt-gh-actions, which I think doesn't distinguish between caches for JVM/JS and thus they end up overriding each other. Also might be complicated to implement.
3. I tried to set this up once and ran into problems with CI release, I think related to the caching thing in (2). So it should be checked if that works (I volunteer bobcats for this).

Linking to https://github.com/typelevel/sbt-typelevel/issues/18 b/c trying to upstream this change to sbt-gh-actions might take longer than absorbing it 🙃

**Comment by rossabaker** [comment]
For smaller projects, I'm less annoyed by CI time.  I like a default that's good for the larger projects.
