### ISSUE TITLE
header check seems to require the year to be 2021

### ISSUE THREAD

**Issue by johnynek** [typelevel/sbt-typelevel#353]
see this PR:

https://github.com/typelevel/cats-parse/pull/438

the first build failed because I copy/pasted the header into new files but updated the year to 2022. When I moved back to 2021 it passed.

**Comment by armanbilge** [comment]
Yes, actually this is set in your build:
https://github.com/typelevel/cats-parse/blob/bcf7dc59eda74d01e6b9f9cd89cc9d9bbcfc57a0/build.sbt#L14

Unfortunately sbt-header does not support different copyright years for different files, feel free to open an issue there.

If you'd rather have full manual control of your copyright headers you can disable the CI check:
```scala
ThisBuild / tlCiHeaderCheck := false
```
