### ISSUE TITLE
Check headers for all Scala versions

### ISSUE THREAD

**Issue by kubukoz** [typelevel/sbt-typelevel#369]
In project that have different source directories depending on the Scala version, it would be useful to have the header check run with `+`:

`sbt +headerCheckAll`.

Same goes for the `prePR` call to `headerCreateAll`.

**Comment by armanbilge** [comment]
Thanks. The `prePR` command should be fixed, but the CI command is already running for every scala version in the matrix.

https://github.com/typelevel/sbt-typelevel/blob/5643503658f627d012546e6544d930c71d1ba240/.github/workflows/ci.yml#L90

**Comment by kubukoz** [comment]
ah, I see. I only hit it in `prePR` so that makes sense.
