### ISSUE TITLE
Disable fatal warnings on 2.12 if cross-building?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#378]
At least a few Typelevel projects are affected by the changes in https://github.com/scala/scala/pull/9890 (particularly those containing JS facades / Native bindings). Actually that PR _improves_ warnings, but the problem is it is a significant divergence from 2.12. This makes cross-compiling across 2.12/2.13 with fatals enabled on both no longer possible, at least with the default sbt-typelevel-settings.

Some random ideas:
1. Disable fatals on 2.12 and move on.
2. Disable just unused warnings on 2.12.
3. Don't warn for ununused nowarns.
4. Create a `@nowarn212`, `@nowarn213`, and `@nowarn3` annotations to help navigate this mess.

/cc @satorg @DavidGregory084 my resident scalac option experts :)

**Comment by som-snytt** [comment]
I think `-Wconf` is a more likely solution.

It would be nice to have a plugin to automate silencing by version, but you're silencing "parameter ... is never used". Or there are "categories" for each flavor. `-Wconf:cat="something"`.

**Comment by satorg** [comment]
@armanbilge just to clarify: you mean sbt-typelevel `0.5.x` line (which is not released yet), but not the `0.4.x` one, don't you?
Because in 0.4 all unused warnings are still disabled for 2.12.

**Comment by armanbilge** [comment]
Oh they are! I completely forgot about that 😂 now I feel silly.

But ok, we still need to think about this for 0.5.x then.

**Comment by som-snytt** [comment]
> all unused warnings are still disabled for 2.12.

I don't use the dis- word anymore, but it would be nice to activate ALL the warnings (insert meme) all the time.

Probably that will be in the form of a `sbt-tpolecat` that enforces a "profile" per version. An ideal was that `-Xlint` enforces a baseline.

But maybe it must have the form of `-Wconf` per version to dial back false positives.

**Comment by satorg** [comment]
> But ok, we still need to think about this for 0.5.x then.

Oh yeah, I do think about it. But the thing is that if we'd like to switch to `scalac-option` while maintaining the same level of option preciseness, we get to extend the latter with several improvements like allowing a particular option to be adjusted in several ways before being rendered into an option string.

> But maybe it must have the form of -Wconf per version to dial back false positives.

Right... There's a great draft proposal in `scalac-option` to extend it with `-Wconf` DSL.
Still may require some refinements to be finally incorporated into the lib.

Then, if we manage to add a possibility to tune `ScalacOption` instance for a particular version range (regardless of whether it is supported or not), then your suggestion will become feasible.

**Comment by som-snytt** [comment]
thanks, I'll look up `scalac-option` as I'm out of the loop. Option precision FTW!

**Comment by satorg** [comment]
@som-snytt it would be great if you could take a look at typelevel/scalac-options#9
and share your thoughts/suggestions in there. thanks!

**Comment by satorg** [comment]
@armanbilge is [this](https://github.com/typelevel/mouse/pull/370#issuecomment-1259005714) thread related to your initial concern?

**Comment by som-snytt** [comment]
I commented on the linked ticket that it should be trivial to use a less-trivial but trivially efficient syntax.

**Comment by DavidGregory084** [comment]
Hmm this one is interesting - so just to state the actual problem clearly, the issue is that:

* The precision of the unused warning was improved in 2.13.9 so that it ignores trivial RHS
* This is causing `@nowarn` annotations that were added to silence previous warnings to trigger their own "does not silence any warnings" warning
* We still get unused warnings for the same code on 2.12, which poses problems for cross-building

I guess the only solution is to add `-Wunused:-nowarn` or `-Wconf:cat=unused-nowarn:silent` for 2.13 only and keep the `@nowarn` annotations? Does that sound right @som-snytt?

**Comment by som-snytt** [comment]
The solution on the `mouse` ticket was to make the RHS less trivial by adding `rhs: Unit`.

I started looking at why the check for unused `@nowarn` is difficult or impossible to suppress selectively. If I figure that out, maybe I can get a solution into 2.13.10.

It seems that having unused `@nowarn` check in `-Xlint:unused` is the hassle for cross-building. In the absence of selective `-Wconf`, I agree that `-Wunused:-nowarn` is simplest way to turn it off.

**Comment by armanbilge** [comment]
@satorg has implemented Scala-version-specific `@nowarn` annotations in https://github.com/http4s/http4s/pull/6751.

**Comment by armanbilge** [comment]
I think scala-compat solves this problem handily. Thank you Sergey!
https://github.com/typelevel/scalac-compat
