### ISSUE TITLE
Incorrect Scala version in publish job matrix config

### ISSUE THREAD

**Issue by jeffmay** [typelevel/sbt-typelevel#391]
Moved from https://github.com/djspiewak/sbt-github-actions/issues/118

> @jeffmay why is the `++` a problem for the publish job? Feel free to open an issue/PR on the sbt-typelevel repo for further discussion.

@armanbilge The problem I'm noticing is that it is assuming the [wrong version for Scala](https://github.com/rallyhealth/scalacheck-ops/pull/62/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR107), so when the workflow runs it issues the commands `++2.12.16 ci-release` to sbt, which fails with the following message:
```
[error] Switch failed: no subprojects list "2.12.16" (or compatible version) in crossScalaVersions setting.
[error] If you want to force it regardless, call ++ 2.12.16!
```

This is because [it should be using the version `2.12.17`](https://github.com/rallyhealth/scalacheck-ops/pull/62/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR26) (or `2.13.10`) to publish the project.

I guess I have 3 questions about this:
1. Where is the plugin getting the version `2.12.16` from? I don't see it anywhere in my SBT config.
2. Is it possible to override this value using `2.12.17` or `2.13.10`? (i.e. to match my versions configured in SBT)
3. If it is only using a single version on a single JVM to run the `ci-release` task, why do we need the config matrix?

**Comment by armanbilge** [comment]
1. This is probably the default `scalaVersion` in sbt.
2. Yes: try setting `ThisBuild / crossScalaVersions := Seq("2.12.17")`
3. You are right, we don't need a matrix for publishing.

**Comment by softinio** [comment]
@armanbilge Out of interest to fix the issue do we want the generated 

`run: sbt '++${{ matrix.scala }}' tlRelease`  

to be 

`run: sbt  tlRelease`? 

or do we still want to specify a scala version? If so, what scala version should it default to (i.e. if `crossScalaVersions` not specified how should it decide what version to use)? 

Unless you are already working on this, will take a stab at doing a PR to fix this if ok? 

Thanks.

**Comment by armanbilge** [comment]
It's already using the default value for `scalaVersion` from sbt. The best way to change it is to manually set `ThisBuild / scalaVersion` (setting `crossScalaVersions` does this implicitly).

I agree we probably don't need it in the generated step. If there's a straightforward fix I think we should consider that. Happy to look at a PR.

**Comment by jeffmay** [comment]
This was fixed by setting `ThisBuild / scalaVersion` to one of the versions in the published by the sbt-projectmatrix generated projects as recommended. Thanks!
