### ISSUE TITLE
Strategically enable/disable bsp

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#405]
A really fantastic idea from @satorg 😃 

```scala
// project/BspControlPlugin.scala

object BspControlPlugin extends AutoPlugin {
  override def trigger = allRequirements
  override def requires = CrossPlugin

  override def projectSettings = Seq(
    Keys.bspEnabled :=
      CrossPlugin.autoImport.crossProjectPlatform.?.value.forall(_ == JVMPlatform)
  )
}
```

It's not right for every project, but this is a good default for the vast majority of projects. Also it's easy enough to opt-out with `.disablePlugins(BspControlPlugin)`.

I am not sure where in sbt-typelevel it should live. I guess it can go in the core plugin.

**Comment by armanbilge** [comment]
I like the idea of a `tlBspPlatforms := Seq(JVMPlatform, NativePlatform)` setting.

**Comment by satorg** [comment]
If I understand the overall idea correctly, we could have the `tlBspPlatforms` setting defined like this:
```scala
lazy val tlBspPlatforms = settingKey[Set[Platform]]("set of platforms for which BSP is enabled (default: JVMPlatform only)")
```
**Q**: `Set` or `Seq`? I like `Set` unless there's a concern about it.

then we could define a default value for it in the global scope:
```scala
override def globalSettings = Set( // or `buildSettings` ?
  tlBspPlatforms := Set(JVMPlatform)
)
```
Finally, we should change `bspEnabled` for each project based on `tlBspPlatforms`:
```scala
  override def projectSettings = Seq(
    Keys.bspEnabled :=
      // keep `bspEnabled := true` for non-crossproject projects
      CrossPlugin.autoImport.crossProjectPlatform.?.value.forall(tlBspPlatforms.value.contains(_))
  )
```

**Comment by armanbilge** [comment]
@satorg yup, that sounds great to me. +1 to `Set`. Feel free to open a PR :)

I think the compatibility implications force us to put it in 0.5.x. We could put it in 0.4.x if we could default the `tlBspPlatforms` to all platforms, but we currently don't have a dependency on the Scala Native crossproject plugin. Maybe we should change that too at this point, lol.

**Comment by satorg** [comment]
I've realized that I owed a PR for this issue. So here it is, finally: #465.
