### ISSUE TITLE
Add `CompileTime` to sbt-typelevel-kernel

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#409]
See https://github.com/http4s/http4s/pull/6751#discussion_r1014595386.

Getting this into sbt would probably be best of all. But I'm confused about https://github.com/sbt/sbt/issues/2503. If they don't want it, we'll take it 😂

**Comment by satorg** [comment]
I think it can go right into `series/0.4` – does not seem to be harmful, wdyt?

**Comment by armanbilge** [comment]
Yup I agree! :)
