### ISSUE TITLE
Proposal: handy SBT commands for compiling sources for a specific platform only

### ISSUE THREAD

**Issue by danicheg** [typelevel/sbt-typelevel#430]
I can be wrong or want unrealistic things, but let me dream a little. Many Typelevel projects are building for JVM/JS/Native platforms at the moment. But sometimes one can develop things only for a specific platform (like JS). Or one wants to get quick feedback from the compiler but doesn't want to wait for the scalac to compile code for all platforms (my case). If we had the handy SBT commands `compileJVM/compileJS/compileNative`, that would be extremely helpful. I'm not sure if it's even technically possible or not, tbh. That said, WDYT?

**Comment by armanbilge** [comment]
You can already do `rootJVM/compile`, `rootJS/compile`, and `rootNative/compile` if you use `tlCrossRootProject`. Does that address your usecase?

**Comment by danicheg** [comment]
> You can already do rootJVM/compile, rootJS/compile, and rootNative/compile if you use tlCrossRootProject. Does that address your usecase?

Thanks for the fast answer! But I thought about the 'topmost' commands, that could be used for every project regardless of how cross-compiling is organized. I mean, in Mouse we have a different structure, it isn't a thing tho, but you have to keep it in mind all the time.

**Comment by armanbilge** [comment]
I see. Why doesn't Mouse use `tlCrossRootProject`?

**Comment by danicheg** [comment]
> Why doesn't Mouse use tlCrossRootProject?

🤷🏻 probably there is no specific reason for that

**Comment by armanbilge** [comment]
That would be my recommendation then. 

> But I thought about the 'topmost' commands, that could be used for every project regardless of how cross-compiling is organized.

To implement this, we would need a way to get a list of projects aggregated in the root that support a specific platform. I'm not really sure of a way to do that "automatically"—this is why `tlCrossRootProject` exists.

**Comment by danicheg** [comment]
> I'm not really sure of a way to do that "automatically"—this is why tlCrossRootProject exists.

Yeah, I was thinking so, and you just confirmed that :(
