### ISSUE TITLE
Optional microsite plugin

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#44]
It doesn't have to be for everyone and it doesn't have to be too fancy. Just something easy.

I had an excellent experience with [laika](https://github.com/planet42/laika) in https://github.com/http4s/http4s-dom/pull/29. There's a lot of boilerplate config in there I think that an opinionated plugin can make go away. The other magic is the [peaceiris action](https://github.com/peaceiris/actions-gh-pages) for publishing to gh-pages. For a simple microsite, it really just works.

Another contender is the new site-generating capabilities in Scaladoc 3, but I haven't experimented with those.

**Comment by rossabaker** [comment]
Yes, a good docs plugin removes much of the boilerplate from a project template.  And Laika's JVM-containment is great.  I lost time again yesterday to jekyll rot.

**Comment by armanbilge** [comment]
https://github.com/typelevel/sbt-typelevel/pull/68
