### ISSUE TITLE
Populate `info.releaseNotesUrl` POM property

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#447]
See:
- https://contributors.scala-lang.org/t/add-release-notes-urls-to-your-poms/6059
- https://github.com/sbt/sbt/issues/7125

**Comment by sideeffffect** [comment]
Is this really needed since TypeLevel projects are hosted on GitHub anyway?
The example from the Contributors forum proves that linking to Release Notes from a PR works out of the box: https://github.com/scala-steward-org/scala-steward/pull/2865
Sorry if I'm missing something :)

**Comment by armanbilge** [comment]
@sideeffffect it's a good question, see:
- https://contributors.scala-lang.org/t/add-release-notes-urls-to-your-poms/6059/3
