### ISSUE TITLE
Show published version in prominent location

### ISSUE THREAD

**Issue by bpholt** [typelevel/sbt-typelevel#450]
When publishing snapshot versions in CI, it can be a little tricky to find the exact version being published in the build output. It's there, and in a consistent place, but the version doesn't stand out in a way that's easy to copy-and-paste. It would be nice to output it in a more prominent location.

One way to do this might be to use [GitHub Action Job Summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/). I've also seen this done by printing the version in a semi-structured way in its own job step.

**Comment by armanbilge** [comment]
This is a good one! Basically we want to add a step here that writes the value of `ThisBuild / version` to the file pointed at by the env variable `GITHUB_STEP_SUMMARY`.

https://github.com/typelevel/sbt-typelevel/blob/5d41b757e1e8099fba133060d7059f6161ef15d6/sonatype-ci-release/src/main/scala/org/typelevel/sbt/TypelevelSonatypeCiReleasePlugin.scala#L62

**Comment by TonioGela** [comment]
I'll take care of the implementation in #451 if you like 😇
