### ISSUE TITLE
Restore `-source:3.2-migration` 

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#474]
- https://github.com/typelevel/sbt-typelevel/pull/467
- https://github.com/typelevel/sbt-typelevel/pull/473

**Comment by armanbilge** [comment]
Btw, I think the lesson learned here is we should try and get out the new flags ahead of Scala releases. Since upgrading a scala (minor) version might always involve work anyway, might as well as do any flag-related work at the same time. But _after_ everyone has upgraded it's extremely annoying to have to make more fixes because of a retro-actively applied flag.

**Comment by armanbilge** [comment]
This seems pretty nuanced ...
- https://github.com/lampepfl/dotty/discussions/17591

**Comment by armanbilge** [comment]
Conclusion in https://github.com/lampepfl/dotty/discussions/17591#discussioncomment-6003589 is that actually we should not use migration flags at all.

**Comment by satorg** [comment]
Do you mean, this issue is better to be closed?

**Comment by armanbilge** [comment]
We can close it after we remove the existing migration flag 😅 
https://github.com/typelevel/sbt-typelevel/blob/5efebdf5350f4e419970ae6906bea385d8381e3f/settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala#L173
