### ISSUE TITLE
Need a way to configure sbt-dependency-submission

### ISSUE THREAD

**Issue by rossabaker** [typelevel/sbt-typelevel#497]
The default sbt-dependency-submission sets off several nuisance alarms on libraries cross built for Scala 3 if we don't exclude the `scala-tool` and `scala-doc-tool` configs.  See https://github.com/scalacenter/sbt-dependency-submission/issues/49.

**Comment by armanbilge** [comment]
I agree, I recently wrote a similar comment on your other issue :)
- https://github.com/typelevel/sbt-typelevel/issues/442#issuecomment-1518456757

**Comment by rossabaker** [comment]
Oops.
