### ISSUE TITLE
Submit Dependencies fails for forks

### ISSUE THREAD

**Issue by j-mie6** [typelevel/sbt-typelevel#566]
The new submit dependencies action in the workflow fails for forks (including of `sbt-typelevel` 😉): can the scope of it running be limited to `main`?

**Comment by j-mie6** [comment]
Actually, this is because the Fork does not have the dependabot integration enabled. Would it work better if this was enabled on `main` and `PR`?

**Comment by armanbilge** [comment]
> can the scope of it running be limited to `main`?

Forks also have a `main` branch. What's the issue with the job failing on the fork?

**Comment by j-mie6** [comment]
They do have a `main` branch, but usually one works on a different branch for PRing back. The issue is that the whole branch CI history is going to never be green-ticked (and every push will incur an email about failed pipeline...)

**Comment by armanbilge** [comment]
Maybe disable CI on the fork completely then? 🤔

**Comment by j-mie6** [comment]
It's a solution, but it's definitely not ideal...

**Comment by armanbilge** [comment]
btw, it looks like it passes on my fork 😛 

https://github.com/armanbilge/sbt-typelevel/actions/runs/5364888442/jobs/9733354787

**Comment by j-mie6** [comment]
Turns out I didn't have read + write permissions enabled for workflows on the fork: this should probably be documented.

**Comment by armanbilge** [comment]
Actually it's documented here. Probably should follow the trouble-shooting guide for the action 😛 

https://github.com/scalacenter/sbt-dependency-submission#troubleshooting

**Comment by j-mie6** [comment]
Fair, might still be worth pointing out in the docs for the relevant `tl` flag
