### ISSUE TITLE
Conflict with `sbt-version-policy`

### ISSUE THREAD

**Issue by durban** [typelevel/sbt-typelevel#568]
`TypelevelMimaPlugin` and `sbt-version-policy` both unconditionally set `mimaPreviousArtifacts`; which means that in a project with both plugins, one overwrites the other (I'm not sure which one, and if it's deterministic). I have [this workaround](https://github.com/durban/choam/blob/734c5b5b/build.sbt#L596) for this. The general problem might not be solvable, but maybe someone has some ideas. See also https://github.com/scalacenter/sbt-version-policy/issues/138.

**Comment by armanbilge** [comment]
Yes, the `TypelevelMimaPlugin` and `sbt-version-policy` should not be used together. They are trying to do the same thing.

**Comment by armanbilge** [comment]
See also this discussion. The algorithm currently used by `sbt-version-policy` may let backwards-compatibility-breaking API changes slip through.

- https://github.com/lightbend/mima/discussions/724#discussioncomment-3765782

**Comment by durban** [comment]
Fair enough. Feel free to close this issue (or it can become a documentation issue, or something).

Btw, I'm only trying to use `sbt-version-policy`, because it does something `sbt-typelevel` doesn't (as far as I know): checking for incompatible dependency updates.

**Comment by armanbilge** [comment]
> checking for incompatible dependency updates.

Oh, neat! Can you point me to that? I've wanted to add this since https://github.com/typelevel/sbt-typelevel/issues/185.

**Comment by j-mie6** [comment]
that would be _awesome_ to have!

**Comment by armanbilge** [comment]
> Btw, I'm only trying to use `sbt-version-policy`, because it does something `sbt-typelevel` doesn't (as far as I know): checking for incompatible dependency updates.

Tracking this feature in https://github.com/typelevel/sbt-typelevel/issues/185.
