### ISSUE TITLE
`sbt 'doc'` task is broken when the project root directory contains a `.`

### ISSUE THREAD

**Issue by CJSmith-0141** [typelevel/sbt-typelevel#618]
I had a project located at [surreal.scala](https://github.com/CJSmith-0141/surreal.scala) that I have since moved to [absurd](https://github.com/CJSmith-0141/absurd).

When this project still had a name with a period in it, the `doc` task was broken on my local machine and then was fixed when I moved it to a new directory without a period.

I think that, if any change in this plugin is even needed (maybe it's an `sbt` bug) the line would be here: https://github.com/typelevel/sbt-typelevel/blob/main/settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala#L216

Maybe related, but probably not: https://github.com/sbt/sbt/issues/7192

**Comment by armanbilge** [comment]
Adding some additional info:

- https://github.com/CJSmith-0141/absurd/commit/ef81efab907cd9bc3b9d8ae51ef5061b760db811
- https://github.com/CJSmith-0141/absurd/actions/runs/5701686350/job/15452638626#step:9:47

```
[error] missing argument for option -sourcepath
[info]   scaladoc -help  gives more information
[info] Skipping unused scalacOptions: -Werror, -Wvalue-discard, -Ykind-projector
[error] (coreJVM / Compile / doc) DottyDoc Compilation Failed
[error] Total time: 1 s, completed Jul 29, 2023, 5:36:16 PM
```

It's also possible that this is a dottydoc bug. Would be interesting to see if Scaladoc for Scala 2 has the same problem.

**Comment by CJSmith-0141** [comment]
Ok I was able to reproduce this with help from @armanbilge and narrowed it down to a bug with dottydoc 

```shell
gh repo clone typelevel/cats cats.scala && cd cats.scala
sbt '++ 3' doc
```
You'll be greeted with may may variations of this error
```shell
[info] Main Scala API documentation to /home/tazato/cats.scala/kernel/.jvm/target/scala-3.3.0/api...
[error] missing argument for option -sourcepath
[info]   scaladoc -help  gives more information
[info] Skipping unused scalacOptions: -Ykind-projector, -source
```
Being that this appears to be a bug with dotty doc I'll close this issue. Thank you for the help narrowing this down!
