### ISSUE TITLE
A way to backpublish tags in CI?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#66]
Noticed this in https://github.com/typelevel/kind-projector/issues/196.

Possibly too esoteric, and kind projector use-case will slowly sunset anyway.

**Comment by rossabaker** [comment]
Arguably the same commit could have just been tagged v0.13.2_2.13.8.  If the automated versioning stripped underscores, it would have worked.

I don't think any of it is worth the effort.

**Comment by rossabaker** [comment]
I'm satisfied with https://github.com/typelevel/kind-projector/pull/205.  We generally want to keep publishing from an existing tag, so changing the build doesn't help, and that shell script gives enough rigor to not mess it up.

**Comment by armanbilge** [comment]
Here's one approach to this: https://github.com/typelevel/kind-projector/pull/206

We could get sbt-typelevel to (optionally) spit out a workflow like this.

**Comment by armanbilge** [comment]
Not enough need for this.

**Comment by kubukoz** [comment]
For anyone looking for something like this, I'm currently using the following:

```scala
/project/backpublish.scala

object BackpublishPlugin extends AutoPlugin {

  override def projectSettings: Seq[Def.Setting[_]] =
    Option(System.getenv("BACKPUBLISH_VERSION")).toList.flatMap { backpublishVersion =>
      val projectVersion = Option(System.getenv("PROJECT_VERSION"))
        .getOrElse(sys.error("No PROJECT_VERSION provided"))

      println(
        s"Going to backpublish artifacts for Scala version $backpublishVersion, project version $projectVersion"
      )

      Seq(
        ThisBuild / version := projectVersion,
        ThisBuild / scalaVersion := backpublishVersion,
        ThisBuild / isSnapshot := false,
        ThisBuild / crossScalaVersions := Seq(backpublishVersion)
      )
    }

}
```

It's a bit hacky and you have to specify the version of the project that you want to backpublish, but it works.

source: https://github.com/polyvariant/better-tostring/tree/39659f635844446aee9799f6816513225e7b3428
