### ISSUE TITLE
Should a docs step be part of the default CI?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#67]
Alongside the current defaults `mimaReportBinaryIssues` and `test`.

http4s uses it, Rob uses it, possibly some other projects I will find out about.

**Comment by rossabaker** [comment]
Absolutely yes.  You can't publish to Maven Central without publishing docs jars (or workarounds), scaladoc is cranky, and I've burned tags on builds that defer this step to publishing.
