### ISSUE TITLE
A potential regression in `v0.7.0`: `HeaderPlugin` throws 'Unable to auto detect project license'

### ISSUE THREAD

**Issue by danicheg** [typelevel/sbt-typelevel#701]
Hey. `mouse` has encountered this when updating to `v0.7.0`:
```
> Check headers and formatting

[error] java.lang.RuntimeException: Unable to auto detect project license
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at de.heikoseeberger.sbtheader.HeaderPlugin$.$anonfun$toBeScopedSettings$9(HeaderPlugin.scala:148)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at de.heikoseeberger.sbtheader.HeaderPlugin$.$anonfun$toBeScopedSettings$8(HeaderPlugin.scala:148)
```
However, the `build.sbt` contains `license` explicitly set:
```
licenses := List(License.MIT)
```
Links:
- [CI run](https://github.com/typelevel/mouse/actions/runs/8767559704/job/24060944910?pr=489#step:8:23)
- [`build.sbt`](https://github.com/typelevel/mouse/blob/main/build.sbt#L18C5-L18C34)

**Comment by armanbilge** [comment]
Maybe because of this?
https://github.com/typelevel/mouse/blob/dfb95570737a4c6039ffdf1bbf938729d56ff34c/build.sbt#L31

tbh I'm not sure what changed in sbt-typelevel that would cause that regression. If you have bandwidth to try some snapshots to bisect it that might help us understand the cause.

**Comment by danicheg** [comment]
I'll give it a try to fix the mouse's CI tomorrow. Anyway, this doesn't appear to be too important. Just curious about the reason.

**Comment by armanbilge** [comment]
> Just curious about the reason.

yes, me too. looks like someone else had the problem as well. I'm genuinely confused what change caused it.

**Comment by danicheg** [comment]
It turned out that adding `startYear` to the root project fixes the issue in `mouse`. Can't say what changes in sbt-typelevel might led to this 🤷🏻

**Comment by mzuehlke** [comment]
#699 stopped setting a wrong `startYear` (as `now` is nearly never the right answer to when a project started.)

**Comment by danicheg** [comment]
@armanbilge aha, gotcha! 😄 
@mzuehlke thanks for pointing this out.

**Comment by mzuehlke** [comment]
sbt-header does a pretty bad job at reporting any errors when detecting the right license 😞 
https://github.com/sbt/sbt-header/blob/master/src/main/scala/de/heikoseeberger/sbtheader/LicenseDetection.scala#L48-L52

**Comment by danicheg** [comment]
Yeah, it's a nice example when `Either` is much better for _enveloping_ errors than `Option` in public API. Also, maybe it'd be a nice contribution.

**Comment by armanbilge** [comment]
I see that Daniel commented on a relevant sbt-header issue in https://github.com/sbt/sbt-header/issues/153#issuecomment-2068570080.

Thanks both for investigating! Looks like this is something that needs to be improved in sbt-header.
