### ISSUE TITLE
Publishing via the Central Portal

### ISSUE THREAD

**Issue by m3is0** [typelevel/sbt-typelevel#721]
Since recently, all new Sonatype accounts must publish via the Central Portal:
[https://central.sonatype.org/register/central-portal/](https://central.sonatype.org/register/central-portal/)

I've successfully published my project with sbt-ci-release and sbt-sonatype v3.11.0 (which supports the new API), 
but with sbt-typelevel-ci-release v0.7.2 (which includes the same sbt-sonatype) it doesn't work.

I tried to set SONATYPE_CREDENTIAL_HOST, but with no success.

**Comment by armanbilge** [comment]
Thanks for trying this!

> it doesn't work.

How do you know that it didn't work? Are there logs or some kind of error message?

**Comment by m3is0** [comment]
As @kubukoz mentioned, I got the following error:
```
scala.MatchError: URLRepository(https://SettingKey(This / This / This / sonatypeCredentialHost), Patterns(ivyPatterns=Vector(), artifactPatterns=Vector(), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), false) (of class sbt.librarymanagement.URLRepository)
	at org.typelevel.sbt.TypelevelSonatypeCiReleasePlugin$.$anonfun$tlCiReleaseCommand$4(TypelevelSonatypeCiReleasePlugin.scala:75)
...
```

**Comment by aartigao** [comment]
FYI, I've tried 👇🏽 

```Scala
addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.7.2-8-ce3d86e-SNAPSHOT")
```

and works! 🎉 Thanks @kubukoz!

(beware that, for the moment, publishing snapshots is not supported and your CI will fail).

**Comment by kubukoz** [comment]
@aartigao did you identify where the problem with snapshots comes from?

**Comment by aartigao** [comment]
If I read correctly it's just that it is not supported yet by SBT Sonatype.

**Comment by m3is0** [comment]
It works well with ```SONATYPE_CREDENTIAL_HOST = "central.sonatype.com"``` as an actions secret!

With ```ThisBuild / sonatypeCredentialHost := xerial.sbt.Sonatype.sonatypeCentralHost``` it doesn't work.

It still uses the default host:
```
2024-07-27 20:14:52.597Z  info [SonatypeService] sonatypeRepository  : https://s01.oss.sonatype.org/service/local  - (SonatypeService.scala:26)
...
2024-07-27 20:14:54.120Z error [Sonatype] 
wvlet.airframe.http.HttpClientException: [401: Unauthorized]
```

Is this expected?

**Comment by m3is0** [comment]
I think the above problem is related to the following code:
https://github.com/typelevel/sbt-typelevel/blob/626ef87136e03ef04b0172ca01d64b4ece698a7d/sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala#L62-L69

**Comment by m3is0** [comment]
Thanks @armanbilge !

**Comment by kubukoz** [comment]
The `0.7.2-12-17ac909-SNAPSHOT` version has [worked for us](https://github.com/siriusxm/snapshot4s), any chance we can get a patch soon?

**Comment by armanbilge** [comment]
@kubukoz we need to fix one more thing before we can release:
- https://github.com/typelevel/sbt-typelevel/issues/735
