### ISSUE TITLE
Should `dependency-submission` job run on push?

### ISSUE THREAD

**Issue by aartigao** [typelevel/sbt-typelevel#723]
According to 👇🏽 

https://github.com/typelevel/sbt-typelevel/blob/775bcd28bc45dab2dd7c8b6c13cf0b95e4c9c148/ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala#L158

it doesn't run on PR, but I still see it run on push 🤔

Is this on purpose?

**Comment by armanbilge** [comment]
Sorry, I'm not sure I understand your question.

It doesn't run for PRs for the reasons explained in https://github.com/typelevel/sbt-typelevel/pull/340#discussion_r947178989.

If it doesn't run on push, then when would it run?

**Comment by aartigao** [comment]
Oh, nevermind. I misunderstood what the action does!
