### ISSUE TITLE
`SONATYPE_CREDENTIAL_HOST` unnecessarily redacted in github actions log

### ISSUE THREAD

**Issue by zarthross** [typelevel/sbt-typelevel#730]
Not sure what can be done, but I was trying to figure out what resolver to add to use a snapshot build of sbt-typelevel and noticed that github automatically censored the resolver in the logs.  Maybe moving it from a github action secret to a github action variable?  Or possibly adding instructions to the readme?  Though i feel fixing it in the logs is wise since that's the place you go to find the snapshot version.

![image](https://github.com/user-attachments/assets/2ef38e9b-71da-4b6f-8c7e-9f961a195a35)

https://github.com/typelevel/sbt-typelevel/actions/runs/10229951814/attempts/1#summary-28304287162

**Comment by armanbilge** [comment]
Aha, this is annoying. Actually an admin should just remove this org-wide secret, we no longer use it. The original idea was to provide a quick way for an entire org to change from the legacy to s01 server without modifying every build.

> to a github action variable

I wonder if these can be set globally. The secret was a bad hack ...

**Comment by zarthross** [comment]
I'm pretty sure you can set an org wide variable: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/variables#creating-configuration-variables-for-an-organization

**Comment by rossabaker** [comment]
Yes, org-wide environment variable is possible.  I can find a reference to the secret in generated ci.yml -- is it going to break anything if we remove that?

**Comment by armanbilge** [comment]
> I can find a reference to the secret in generated ci.yml -- is it going to break anything if we remove that?

It's not, because we've already updated all the builds. sbt-typelevel now uses the s01 host by default, it no longer needs to be configured.

**Comment by rossabaker** [comment]
Okay, I just migrated the secret to an environment variable, org wide.

**Comment by armanbilge** [comment]
Thanks! Let's keep this issue open until we change sbt-typelevel to read this from the env instead of the secret.

**Comment by zarthross** [comment]
We'll know for sure next time a release is cut or a PR is merged...

**Comment by zarthross** [comment]
This appears to be fixed now.  Thanks all!

![image](https://github.com/user-attachments/assets/3fb25369-385c-4da3-ad52-d0c91263a986)
