### ISSUE TITLE
Disable snapshots when publishing to central portal

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#735]
> The Central Publisher Portal does not support -SNAPSHOT releases, and deployments of -SNAPSHOT releases will have a version cannot be a SNAPSHOT error in their validation results. Versions should only be published to the Portal if they are intended to reach Maven Central.

https://central.sonatype.org/faq/snapshot-releases/

**Comment by kubukoz** [comment]
"Disable snapshots", or "remove the -SNAPSHOT suffix"?

in other words, what do we mean by disabling?

**Comment by armanbilge** [comment]
Good news, looks like they've added support for snapshots :)

https://central.sonatype.org/publish/publish-portal-snapshots/
