### ISSUE TITLE
Steward PRing sbt-typelevel updates?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#78]
I've been watching doobie which is currently on sbt-typelevel v0.4.0-M3 hoping that it will get a Steward update to M4 which was released a couple days ago, but so far this hasn't happened.
https://github.com/tpolecat/doobie/blob/59bf85ab1a8482abd18ba9f026c43ee9d48e304b/project/plugins.sbt#L4

Now more projects are using sbt-typelevel, and I just cut an M5 with a bug fix, so I want to make sure updates are working.

@fthomas would you mind helping with this? Thank you :)

**Comment by fthomas** [comment]
@armanbilge Can you give me the URL to the M4 or M5 jar? I can't find it in Scala Steward's versions cache.

**Comment by armanbilge** [comment]
@fthomas this one? https://repo1.maven.org/maven2/org/typelevel/sbt-typelevel_2.12_1.0/0.4.0-M4/

**Comment by fthomas** [comment]
Yes, thank you.

Scala Steward couldn't find the `maven-metadata.xml` for that artifact:
```
cat https/repo1.maven.org/maven2/org/typelevel/sbt-typelevel-ci-release_2.12_1.0/versions.json 
{
  "updatedAt" : 1642494532323,
  "versions" : [
  ],
  "maybeError" : "java.lang.Throwable: not found: https://repo1.maven.org/maven2/org/typelevel/sbt-typelevel-ci-release_2.12_1.0/maven-metadata.xml"
}
```

**Comment by armanbilge** [comment]
Oh, interesting, thanks. I bet this also explains https://github.com/maxcellent/javadoc.io/issues/85. I'll try and chase this down.

**Comment by armanbilge** [comment]
But how do updates work for other sbt plugins? I don't see a `versions.json` for sbt-github-actions for example.
https://repo1.maven.org/maven2/com/codecommit/sbt-github-actions_2.12_1.0/0.14.2/

**Comment by fthomas** [comment]
```
cat https/repo1.maven.org/maven2/com/codecommit/sbt-github-actions_2.12_1.0/versions.json 
{
  "updatedAt" : 1642506718609,
  "versions" : [
    "0.11.0",
    "0.12.0",
    "0.13.0",
    "0.14.0",
    "0.14.1",
    "0.14.2"
  ],
  "maybeError" : null
}
```
It knows about all versions except 0.11-3de77fa and 0.11-e6116b4. Maybe pre-release versions are not included in the versions reported by Coursier for sbt plugins.

**Comment by armanbilge** [comment]
Thanks, I'll follow up with Coursier ... is there a workaround we can do in the meantime?

**Comment by fthomas** [comment]
Yes, stop using pre-releases. :-)

**Comment by armanbilge** [comment]
@rossabaker wdyt about going straight to 0.4.0?

**Comment by armanbilge** [comment]
Related: https://github.com/sbt/sbt/issues/3879

**Comment by fthomas** [comment]
Btw, I briefly looked into Coursier if it is possible to reproduce this on the command-line but it seems currently to be impossible to list available versions of sbt plugins: https://github.com/coursier/coursier/issues/2178.

**Comment by armanbilge** [comment]
Yep, I discovered the same. I bet it all has to do with this missing `maven-metadata.xml`.

**Comment by fthomas** [comment]
Found why Coursier reports no versions for sbt-typelevel: https://github.com/coursier/coursier/blob/master/modules/core/shared/src/main/scala/coursier/maven/MavenRepository.scala#L249 If the directory listing only contains pre-release versions, no versions are reported.

**Comment by fthomas** [comment]
I don't think so. Only non pre-release versions are reported in https://github.com/coursier/coursier/blob/b5d5429a909426f4465a9599d25c678189a54549/modules/core/shared/src/main/scala/coursier/maven/MavenRepository.scala#L252-L257

**Comment by armanbilge** [comment]
Ok, thanks for all your help, much appreciated. Would be nice if this one day can be fixed upstream (I assume that would be coursier) but for now our best option is probably to go to 0.4.0.

**Comment by armanbilge** [comment]
Alright, seems to be working :) thank you steward and thank you @fthomas ❤️

BTW the maven issues with sbt plugins will almost definitely be fixed in sbt 2 it seems like.
- https://github.com/sbt/sbt/issues/3410
