### ISSUE TITLE
Fail silently on artifact upload/download steps?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#81]
These seem to flake occasionally and are not really critical, just shuffling caches to save recompilation during the release job. So it would probably be okay for them to fail silently.

An example in https://github.com/typelevel/jawn/runs/4859261390?check_suite_focus=true#step:14:1.

```
Run actions/upload-artifact@v2
With the provided path, there will be 1 file uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "target-ubuntu-latest-2.13.8-temurin@8" successfully created. Starting upload of file(s)
Uploaded /home/runner/work/jawn/jawn/targets.tar (81.2%) bytes 0:8388607
A 503 status code has been received, will attempt to retry the upload
Exponential backoff for retry #1. Waiting for 5499 milliseconds before continuing the upload at offset 8388608
Finished backoff for retry #1, continuing with upload
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/dr4d5xdeYJVOyUhrZtz8KK0R6jc49DIbpbB6Fk82oUW560k70a/_apis/resources/Containers/12175527?itemPath=target-ubuntu-latest-2.13.8-temurin%408%2Ftargets.tar
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "d1684538-5dcb-4a3f-8745-537477d6a514",
  "activityid": "451083d9-565b-4d05-bc87-ee9e822f2860",
  "x-tfs-session": "451083d9-565b-4d05-bc87-ee9e822f2860",
  "x-vss-e2eid": "451083d9-565b-4d05-bc87-ee9e822f2860",
  "x-vss-senderdeploymentid": "02120909-3c00-63c2-b451-f147b8aff5a4",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 4C7B648E7A42422797C334697F30AC46 Ref B: SN1EDGE1721 Ref C: 2022-01-18T20:58:59Z",
  "date": "Tue, 18 Jan 2022 20:58:58 GMT"
}
###### End Diagnostic HTTP information ######
Warning: Aborting upload for /home/runner/work/jawn/jawn/targets.tar due to failure
Error: aborting artifact upload
```

**Comment by armanbilge** [comment]
Could be related to https://github.com/typelevel/sbt-typelevel/issues/74, but I doubt it.

**Comment by armanbilge** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

Not sure if sbt-gh-actions supports this ATM.

**Comment by armanbilge** [comment]
Another upload failure in https://github.com/http4s/http4s-dom/pull/82. I've never seen these before and now they seem to happen semi-frequently.

**Comment by armanbilge** [comment]
Ugh, another one in https://github.com/typelevel/shapeless-3/pull/66.

**Comment by rossabaker** [comment]
I think that would be reasonable.

**Comment by armanbilge** [comment]
I think disabling for PRs in https://github.com/typelevel/sbt-typelevel/issues/89 is the easy first step. Doing this probably requires more significant changes to sbt-github-actions which I'm trying to be conservative about at the moment (and also may have bincompat implications).

**Comment by armanbilge** [comment]
If someone would like to help debug this, apparently we can get more detailed logs by setting the `ACTIONS_STEP_DEBUG` secret to `true`. It won't help with PRs obviously since those can't access secrets.

I'm more suspicious it's related to https://github.com/typelevel/sbt-typelevel/issues/74 based on the repositories I've been observing this in.

**Comment by armanbilge** [comment]
This might be https://github.com/typelevel/sbt-typelevel/issues/74 after all. Except we are getting 400 and not 503.

> Warning: Be careful when uploading to the same artifact via multiple jobs as artifacts may become corrupted. When uploading a file with an identical name and path in multiple jobs, uploads may fail with 503 errors due to conflicting uploads happening at the same time. Ensure uploads to identical locations to not interfere with each other.

https://github.com/actions/upload-artifact#uploading-to-the-same-artifact

**Comment by armanbilge** [comment]
This is probably fixed so I'm going to close. We can reopen if problems surface.
