### ISSUE TITLE
TypelevelSitePlugin assumes site is in a directory called docs

### ISSUE THREAD

**Issue by rossabaker** [typelevel/sbt-typelevel#95]
https://github.com/typelevel/cats-uri/runs/4909193164?check_suite_focus=true#step:5:30

**Comment by armanbilge** [comment]
Oh yeah, those may be baked in a little too hard. I just followed the instructions for mdoc.

```scala
lazy val docs = project       // new documentation project
  .in(file("myproject-docs")) // important: it must not be docs/
  .dependsOn(myproject)
  .enablePlugins(MdocPlugin)
```

> Next, from the sbt shell, run the `docs/mdoc` task to generate the documentation site. By default, the mdoc task looks for markdown sources in the toplevel `docs/` directory.

https://scalameta.org/mdoc/docs/installation.html#sbt
